import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import React, {Suspense} from "react";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'CustomAIzed',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <html lang="en">
      <body>
      <section>
        <Suspense
            fallback={
              <div className="flex w-full px-4 lg:px-40 py-4 items-center border-b text-center gap-8 justify-between h-[69px]" />
            }
        >
          <NavBar />
        </Suspense>
      </section>
      <main className="flex flex-1 flex-col items-center py-16">
        {children}
      </main>
      <Footer />
      </body>
      </html>
  );
}
